-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
BEGIN;
ALTER TABLE public."tbl_Country"
    SET WITHOUT OIDS;

ALTER TABLE public."tbl_Country" DROP COLUMN "CountryDisplayName";

ALTER TABLE public."tbl_Country" DROP COLUMN "CountryAbbrev";

ALTER TABLE public."tbl_Country" DROP COLUMN "CountryCode";

ALTER TABLE public."tbl_Country" DROP COLUMN "CurrencyID";

ALTER TABLE public."tbl_Country" DROP COLUMN "RegionID";

ALTER TABLE public."tbl_Country" DROP COLUMN "CreatedBy";

ALTER TABLE public."tbl_Country" DROP COLUMN "CreatedDate";

ALTER TABLE public."tbl_Country" DROP COLUMN "ModifiedBy";

ALTER TABLE public."tbl_Country" DROP COLUMN "ModifiedDate";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CountryID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Country"
 --     ALTER COLUMN "CountryID" TYPE integer;
ALTER TABLE public."tbl_Country"
    ALTER COLUMN "CountryID" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CountryName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Country"
 --     ALTER COLUMN "CountryName" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Country"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_Country"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Country"
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public."tbl_Country"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "CountrySort" integer;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "GeoschemeID" integer;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "IsoCountryID" integer;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "IsoCountryAlpha2" character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public."tbl_Country"
    ADD COLUMN "IsoCurrencyID" integer;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "DialCodePrimary" integer;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "DialCodeSecondary" double precision;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedSalesTax" double precision;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedSalesTaxName" character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedTaxUpdatedOn" timestamp(3) without time zone;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedTaxWireless" double precision;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedTaxWirelessName" character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedTaxWirelessUpdatedOn" timestamp(3) without time zone;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedTaxInternet" double precision;

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedTaxInternetName" character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public."tbl_Country"
    ADD COLUMN "FedTaxInternetUpdatedOn" timestamp(3) without time zone;
-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the DiscountOptionID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_DiscountOptions"
 --     ALTER COLUMN "DiscountOptionID" TYPE double precision;
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "DiscountOptionID" DROP DEFAULT;

ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "DiscountOptionID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the DiscountOptionShortName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_DiscountOptions"
 --     ALTER COLUMN "DiscountOptionShortName" TYPE character varying(255) COLLATE pg_catalog."default";
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "DiscountOptionShortName" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the DiscountOptionName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_DiscountOptions"
 --     ALTER COLUMN "DiscountOptionName" TYPE character varying(255) COLLATE pg_catalog."default";
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "DiscountOptionName" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ToolTipDescription column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_DiscountOptions"
 --     ALTER COLUMN "ToolTipDescription" TYPE character varying(255) COLLATE pg_catalog."default";
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "ToolTipDescription" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_DiscountOptions"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_DiscountOptions"
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_DiscountOptions"
 --     ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_DiscountOptions"
 --     ALTER COLUMN "ModifiedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_DiscountOptions"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;
ALTER TABLE public."tbl_DiscountOptions" DROP CONSTRAINT "tbl_DiscountOptions_pkey";
ALTER TABLE public."tbl_ItemRegister"
    SET WITHOUT OIDS;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemRegisterID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ItemRegisterID" TYPE integer;
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ItemRegisterID" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the SubPlanTypeID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "SubPlanTypeID" TYPE integer;
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "SubPlanTypeID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemTypeID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ItemTypeID" TYPE integer;
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ItemTypeID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemConfigurationID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ItemConfigurationID" TYPE integer;
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ItemConfigurationID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureTypeID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ItemUnitMeasureTypeID" TYPE integer;
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ItemUnitMeasureTypeID" DROP NOT NULL;

ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ShowSelecting" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemRegisterName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ItemRegisterName" TYPE character varying(255) COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ItemRegisterName" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemRegisterDisplay column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ItemRegisterDisplay" TYPE character varying(255) COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ItemRegisterDisplay" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemRegisterDescription column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ItemRegisterDescription" TYPE character varying(255) COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ItemRegisterDescription" DROP NOT NULL;

ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "IsActive" DROP DEFAULT;

ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedDate column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ModifiedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedDate column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IconPath column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemRegister"
 --     ALTER COLUMN "IconPath" TYPE character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ShowDetailing" DROP DEFAULT;

ALTER TABLE public."tbl_ItemRegister"
    ALTER COLUMN "ShowEditing" DROP DEFAULT;

ALTER TABLE public."tbl_ItemRegister"
    ADD COLUMN "Oid" double precision;

ALTER TABLE public."tbl_ItemRegister"
    ADD COLUMN "ShowCompare" boolean NOT NULL;

ALTER TABLE public."tbl_ItemRegister"
    ADD COLUMN "ValueContributionFactor" smallint;
ALTER TABLE public."tbl_ItemRegister" DROP CONSTRAINT "tbl_ItemRegister_ItemRegisterID";
ALTER TABLE public."tbl_ItemUnitMeasure"
    SET WITHOUT OIDS;

ALTER TABLE public."tbl_ItemUnitMeasure" DROP COLUMN "ItemUnitMeasureOrder";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ItemUnitMeasureID" TYPE integer;
ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "ItemUnitMeasureID" DROP DEFAULT;

ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "ItemUnitMeasureID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureTypeID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ItemUnitMeasureTypeID" TYPE integer;
ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "ItemUnitMeasureTypeID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ItemUnitMeasureName" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureDisplay column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ItemUnitMeasureDisplay" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureAbbrev column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ItemUnitMeasureAbbrev" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitQtyOverride column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ItemUnitQtyOverride" TYPE double precision COLLATE pg_catalog."default";

ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "ItemUnitQtyOverride" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureRatio column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ItemUnitMeasureRatio" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureConvertUp column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ItemUnitMeasureConvertUp" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the Description column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "Description" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "CreatedBy" TYPE integer COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ItemUnitMeasure"
 --     ALTER COLUMN "ModifiedBy" TYPE integer COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_ItemUnitMeasure"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

ALTER TABLE public."tbl_ItemUnitMeasure"
    ADD COLUMN "Oid" double precision;

ALTER TABLE public."tbl_ItemUnitMeasure"
    ADD COLUMN "ItemUnitMeasuReorder" integer;
ALTER TABLE public."tbl_Provider"
    SET WITHOUT OIDS;

ALTER TABLE public."tbl_Provider" DROP COLUMN "prvNetwork";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "ProviderID" TYPE integer;
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "ProviderID" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "ProviderName" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderDisplay column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "ProviderDisplay" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderAbbrv column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "ProviderAbbrv" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the AddressID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "AddressID" TYPE double precision;
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "AddressID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the SubPlanTypeID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "SubPlanTypeID" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the RegionID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "RegionID" TYPE double precision;
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "RegionID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the MarketSegmentID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "MarketSegmentID" TYPE double precision;
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "MarketSegmentID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CountryID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "CountryID" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the WebAddr column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "WebAddr" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the EmailAddr column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "EmailAddr" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the SubscriberTelNo column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "SubscriberTelNo" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProspectTelNo column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "ProspectTelNo" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the BckgrColor column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "BckgrColor" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ForeColor column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "ForeColor" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CardColor column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "CardColor" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_Provider"
 --     ALTER COLUMN "ModifiedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_Provider"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

ALTER TABLE public."tbl_Provider"
    ADD COLUMN "Oid" double precision;

ALTER TABLE public."tbl_Provider"
    ADD COLUMN "PrvnetWork" character varying(255) COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ProviderPlan"
    SET WITHOUT OIDS;

ALTER TABLE public."tbl_ProviderPlan" DROP COLUMN "ExpiresToID";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderPlanID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "ProviderPlanID" TYPE double precision;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "ProviderPlanID" DROP DEFAULT;

ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "ProviderPlanID" DROP NOT NULL;

ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the SubPlanTypeID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "SubPlanTypeID" TYPE integer;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "SubPlanTypeID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "ProviderID" TYPE double precision;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "ProviderID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderPlanName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "ProviderPlanName" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderPlanDisplay column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "ProviderPlanDisplay" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderPlanAbbrev column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "ProviderPlanAbbrev" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the PlanBaseCost column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "PlanBaseCost" TYPE double precision COLLATE pg_catalog."default";

ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "PlanBaseCost" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the Description column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "Description" TYPE character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "ExpiresOn" TYPE timestamp(3) without time zone ;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsAvailable column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "IsAvailable" TYPE boolean;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "IsAvailable" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsSelectable column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "IsSelectable" TYPE boolean;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "IsSelectable" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "CreatedBy" TYPE integer COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlan"
 --     ALTER COLUMN "ModifiedBy" TYPE integer COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_ProviderPlan"
    ALTER COLUMN "AvailableOn" TYPE timestamp(3) without time zone ;

ALTER TABLE public."tbl_ProviderPlan"
    ADD COLUMN "Oid" double precision;

ALTER TABLE public."tbl_ProviderPlan"
    ADD COLUMN "ExpiresToId" double precision;
ALTER TABLE public."tbl_ProviderPlanItem"
    SET WITHOUT OIDS;

ALTER TABLE public."tbl_ProviderPlanItem" DROP COLUMN "IsDelete";

ALTER TABLE public."tbl_ProviderPlanItem" DROP COLUMN "ModifiedBy";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderPlanItemID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "ProviderPlanItemID" TYPE double precision;
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ProviderPlanItemID" DROP DEFAULT;

ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ProviderPlanItemID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderPlanID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "ProviderPlanID" TYPE double precision;
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ProviderPlanID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemRegisterID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "ItemRegisterID" TYPE double precision;
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ItemRegisterID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemNo column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "ItemNo" TYPE smallint;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderPlanItemDisplay column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "ProviderPlanItemDisplay" TYPE character varying(255) COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ProviderPlanItemDisplay" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ParentID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "ParentID" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the SiblingID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "SiblingID" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the HasChildren column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "HasChildren" TYPE boolean;
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "HasChildren" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the RollupQtyItm column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "RollupQtyItm" TYPE smallint;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the Quantity column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "Quantity" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ItemUnitMeasureID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "ItemUnitMeasureID" TYPE double precision;
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ItemUnitMeasureID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the QuantityValue column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "QuantityValue" TYPE real;

ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ExpiresOn" TYPE timestamp(3) without time zone ;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ExpiresToID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "ExpiresToID" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_ProviderPlanItem"
 --     ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_ProviderPlanItem"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

ALTER TABLE public."tbl_ProviderPlanItem"
    ADD COLUMN "Oid" double precision;

ALTER TABLE public."tbl_ProviderPlanItem"
    ADD COLUMN "Isdelete" boolean NOT NULL;

ALTER TABLE public."tbl_ProviderPlanItem"
    ADD COLUMN modifiedby double precision;
ALTER TABLE public."tbl_UserPreference"
    SET WITHOUT OIDS;

ALTER TABLE public."tbl_UserPreference" DROP COLUMN "Phonelinecount";

ALTER TABLE public."tbl_UserPreference" DROP COLUMN "Datalowerlimit";

ALTER TABLE public."tbl_UserPreference" DROP COLUMN "Dataupperlimit";

ALTER TABLE public."tbl_UserPreference" DROP COLUMN userproviderplanid;

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "UserPreferenceID" TYPE double precision;
ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "UserPreferenceID" DROP DEFAULT;

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "UserPreferenceID" DROP NOT NULL;

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "UserProfileID" TYPE double precision;
ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "UserProfileID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CompareOrTrack column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserPreference"
 --     ALTER COLUMN "CompareOrTrack" TYPE character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "UserPlanSavingCost" TYPE double precision;

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "OtherPlanSavingCost" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the PlanID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserPreference"
 --     ALTER COLUMN "PlanID" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserPreference"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserPreference"
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedDate column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserPreference"
 --     ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "ModifiedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedDate column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserPreference"
 --     ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_UserPreference"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the UserPlanName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserPreference"
 --     ALTER COLUMN "UserPlanName" TYPE character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public."tbl_UserPreference"
    ADD COLUMN "PhoneLineCount" double precision;

ALTER TABLE public."tbl_UserPreference"
    ADD COLUMN "DataLowerLimit" double precision;

ALTER TABLE public."tbl_UserPreference"
    ADD COLUMN "DataUpperLimit" double precision;

ALTER TABLE public."tbl_UserPreference"
    ADD COLUMN "UserProviderPlanID" character varying(255) COLLATE pg_catalog."default";
DROP TRIGGER trb_userpreference ON public."tbl_UserPreference";
DROP TRIGGER tra_userpreference ON public."tbl_UserPreference";
ALTER TABLE public."tbl_UserProfile"
    SET WITHOUT OIDS;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the UserProfileID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "UserProfileID" TYPE double precision;
ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "UserProfileID" DROP DEFAULT;

ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "UserProfileID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the AddressID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "AddressID" TYPE integer;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the FirstName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "FirstName" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the MiddleName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "MiddleName" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the LastName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "LastName" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the Email column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "Email" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the UserName column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "UserName" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the Password column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "Password" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the PasswordSalt column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "PasswordSalt" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the PasswordHint column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "PasswordHint" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CountryCode column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "CountryCode" TYPE integer COLLATE pg_catalog."default";

ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "CountryCode" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the MobileNo column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "MobileNo" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile"
 --     ALTER COLUMN "ModifiedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_UserProfile"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

ALTER TABLE public."tbl_UserProfile"
    ADD COLUMN "Oid" double precision;
ALTER TABLE public."tbl_UserProfile" DROP CONSTRAINT "tbl_UserProfile_UserProfileID";
DROP TRIGGER tr_userprofile ON public."tbl_UserProfile";
-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the UserDiscountProfileID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile_Discount"
 --     ALTER COLUMN "UserDiscountProfileID" TYPE double precision;
ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "UserDiscountProfileID" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the UserProfileID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile_Discount"
 --     ALTER COLUMN "UserProfileID" TYPE double precision;
ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "UserProfileID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the DiscountOptions column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile_Discount"
 --     ALTER COLUMN "DiscountOptions" TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile_Discount"
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile_Discount"
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "IsDelete" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile_Discount"
 --     ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."tbl_UserProfile_Discount"
 --     ALTER COLUMN "ModifiedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public."tbl_UserProfile_Discount"
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;
ALTER TABLE public."tbl_UserProfile_Discount" DROP CONSTRAINT "tbl_UserProfile_UserDisctProfileID";
DROP TRIGGER tra_userdiscountprofile ON public."tbl_UserProfile_Discount";
DROP TRIGGER tr_userdiscountprofile ON public."tbl_UserProfile_Discount";
ALTER TABLE public.tbl_userproviderplan
    SET WITHOUT OIDS;

ALTER TABLE public.tbl_userproviderplan DROP COLUMN "UserProfileID";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the userproviderplanid column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN userproviderplanid TYPE double precision;
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN userproviderplanid DROP DEFAULT;

ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN userproviderplanid DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderplanID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN "ProviderplanID" TYPE double precision;
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "ProviderplanID" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the UserPreferenceID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN "UserPreferenceID" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the userplanname column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN userplanname TYPE character varying(255) COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the userplanbasecost column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN userplanbasecost TYPE double precision COLLATE pg_catalog."default";

ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN userplanbasecost SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsAvailable column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN "IsAvailable" TYPE boolean;
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "IsAvailable" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsSelectable column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN "IsSelectable" TYPE boolean;
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "IsSelectable" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "IsDelete" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedBy column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplan
 --     ALTER COLUMN "ModifiedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public.tbl_userproviderplan
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplan
    ADD COLUMN oid double precision NOT NULL;

ALTER TABLE public.tbl_userproviderplan
    ADD COLUMN "UserProfileId" double precision;
DROP TRIGGER tr_userproviderplan ON public.tbl_userproviderplan;
ALTER TABLE public.tbl_userproviderplanitem
    SET WITHOUT OIDS;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN userproviderplanitemid TYPE double precision;
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN userproviderplanitemid DROP DEFAULT;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN userproviderplanitemid DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN userproviderplanid TYPE double precision;
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN userproviderplanid DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ItemRegisterID" TYPE smallint;
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ItemRegisterID" DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ItemNo" TYPE smallint;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ProviderPlanItemDisplay column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplanitem
 --     ALTER COLUMN "ProviderPlanItemDisplay" TYPE character varying(255) COLLATE pg_catalog."default";

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ParentID" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the HasChildren column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplanitem
 --     ALTER COLUMN "HasChildren" TYPE boolean;
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "HasChildren" DROP DEFAULT;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "HasChildren" SET NOT NULL;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ItemUnitMeasureID" TYPE double precision;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsActive column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplanitem
 --     ALTER COLUMN "IsActive" TYPE boolean;
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "IsActive" DROP DEFAULT;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the IsDelete column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplanitem
 --     ALTER COLUMN "IsDelete" TYPE boolean;
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "IsDelete" DROP DEFAULT;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "CreatedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "CreatedBy" DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "CreatedBy" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the CreatedDate column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplanitem
 --     ALTER COLUMN "CreatedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "CreatedDate" DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ModifiedBy" TYPE double precision COLLATE pg_catalog."default";
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ModifiedBy" DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ModifiedBy" SET STORAGE PLAIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ModifiedDate column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public.tbl_userproviderplanitem
 --     ALTER COLUMN "ModifiedDate" TYPE timestamp(3) without time zone ;
ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN "ModifiedDate" DROP NOT NULL;

ALTER TABLE public.tbl_userproviderplanitem
    ALTER COLUMN providerplanid TYPE double precision;
ALTER TABLE public.tbl_userproviderplanitem DROP CONSTRAINT tbl_userproviderplanitem_userproviderplanitemid;
DROP TRIGGER tr_userproviderplanitem ON public.tbl_userproviderplanitem;

END;